name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Init Java
      uses: actions/setup-java@v1.0.0
    - name: Run all Java files
      run: |
        javac CompileJava.java
        java CompileJava
        rm CompileJava.class
